"""init pnao schema

Revision ID: a40552e60968
Revises: 
Create Date: 2025-12-18 15:34:56.337909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a40552e60968'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pnao'
    )
    op.create_index(op.f('ix_pnao_raw_data_source'), 'raw_data', ['source'], unique=False, schema='pnao')
    op.create_index('ix_raw_data_payload_gin', 'raw_data', ['payload'], unique=False, schema='pnao', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_data_payload_gin', table_name='raw_data', schema='pnao', postgresql_using='gin')
    op.drop_index(op.f('ix_pnao_raw_data_source'), table_name='raw_data', schema='pnao')
    op.drop_table('raw_data', schema='pnao')
    # ### end Alembic commands ###
